# Generated by Django 4.1.7 on 2023-03-25 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOfStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Номер курса')),
            ],
            options={
                'verbose_name': 'Номер курса',
                'verbose_name_plural': 'Номера курсов',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название группы')),
                ('directionStudy', models.CharField(max_length=250, verbose_name='Номер направления')),
            ],
            options={
                'verbose_name': 'Название группы и направление',
                'verbose_name_plural': 'Названия групп и направлений',
            },
        ),
        migrations.CreateModel(
            name='Hilary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название сдаваемой сессии')),
            ],
            options={
                'verbose_name': 'Название сессии',
                'verbose_name_plural': 'Названия сессий',
            },
        ),
        migrations.CreateModel(
            name='All',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=250, verbose_name='ФИО')),
                ('mail', models.EmailField(max_length=250, verbose_name='Почта обучаемого')),
                ('formOfStudy', models.CharField(choices=[('У', 'Удаленная форма обучения'), ('З', 'Заочная форма обучения'), ('О', 'Очная форма обучения')], max_length=1, verbose_name='Форма обучения')),
                ('courseOfStudy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.courseofstudy')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.group')),
                ('hilary_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.hilary')),
            ],
            options={
                'verbose_name': 'Запись с учеником',
                'verbose_name_plural': 'Записи с учениками',
            },
        ),
    ]
