# Generated by Django 4.2 on 2023-04-05 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название предмета')),
            ],
            options={
                'verbose_name': 'Название предмета',
                'verbose_name_plural': 'Названия предметов',
            },
        ),
        migrations.AlterField(
            model_name='all',
            name='courseOfStudy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.courseofstudy', verbose_name='Номер курса'),
        ),
        migrations.AlterField(
            model_name='all',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='all',
            name='hilary_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.hilary', verbose_name='Сдаваемая сессия'),
        ),
        migrations.AddField(
            model_name='all',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.item', verbose_name='Необходимый предмет'),
        ),
    ]
